name: release

on:
  workflow_dispatch:

jobs:
  run:
    name: test-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup package
        run: yarn install

      - name: Get version from package.json
        uses: actions/github-script@v3.1.0
        id: version
        with:
          result-encoding: string
          script: |
            const version = require(`${process.env.GITHUB_WORKSPACE}/package.json`).version;
            core.setOutput('repo', context.repo.repo);
            core.setOutput('version', version);

      - name: Publish package
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: yarn run deploy
